export const SET_USER_INFO = "SET_USER_INFO";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_STATE = "CLEAR_STATE";

export const SET_AUTHENTICATING = "SET_AUTHENTICATING";
export const RESET_AUTHENTICATING = "RESET_AUTHENTICATING";
